Project setup
phylischumba/Calculator-React pull request #1
Opened 2020-09-22 10:38 UTC by Phylis05

### Milestone One

- Delete any unnecessary file or asset
- Add prop-types and big.js using npm
- Run the application with npm start and make sure that everything works correctly.
- Initialize a git repo
- Deploy to Heroku

2020-09-22 16:18 UTC, bellom requested changes
## Hi @Phylis05  :clap: 

### Awesome job so far!! :+1: 

#### You have done wonderfully well, you passed `almost` all the checklist for this project :+1: just a few issues left to work on............ :slightly_smiling_face: 
 
**Kindly check out my comments below;**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

2020-09-22 16:18 UTC, bellom commented on README.md
> +# Calculator-React
**Let's make your repo looks professional by applying all the 3 basic rules, kindly update your `README` file and remove unnecessary content**.
Checkout out the template for help, free free to follow this [template](https://github.com/microverseinc/readme-template) from pathwright

![image](https://user-images.githubusercontent.com/31897434/92685488-b4c45680-f32f-11ea-9bea-222a21c096a6.png)

https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/

2020-09-22 19:43 UTC, Phylis05 commented
Hey @bellom, thanks for the review. I have implemented the changes requested.

2020-09-23 10:13 UTC, Oghenebrume50 approved these changes
### APPROVED 

Good job making changes @Phylis05  the project could actually use some cleanup in the readme and be more professional but this is good for now :slightly_smiling_face: Please merge and move on **This is approved** :+1: 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-09-23 12:00 UTC, Phylis05 commented
Thank you @Oghenebrume50. I will look into it as I proceed

2020-09-23 12:01 UTC, merged