Milestone Three: Style Components
phylischumba/Calculator-React pull request #3
Opened 2020-09-24 05:11 UTC by Phylis05

## Add styles to the project
- Added style to the components
- Added props to the button component
- Fix linter errors

2020-09-24 19:06 UTC, Oghenebrume50 requested changes
### CHANGES REQUIRED

Hi @Phylis05 you did well with this implementation, it looks really nice but you want the App component to  have flex display 
![see this](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/react_reducx/calculator/milestone3/useFlex.png)

**Please make changes and Request for another review** 

**RAPHAEL NORIODE** :mask: STAY_SAFE

2020-09-24 19:43 UTC, Phylis05 commented
Hey @Oghenebrume50,

Thanks for the review. I have implemented the change you just requested

2020-09-24 22:28 UTC, shloch requested changes
## Hello @Phylis05 

Hello Great job .........
SOrry i will have to come back to some errors which is very important

- I have console errors, please debug this
![calc](https://user-images.githubusercontent.com/40712459/94206152-af811300-febc-11ea-97dd-3657690d7ed4.gif)

## [optional]
- it's about the comment below

Happy coding

2020-09-24 22:28 UTC, shloch commented on src/index.css
>  }
you can center the app, for symmetry
```
margin: auto;
```

2020-09-25 02:59 UTC, Phylis05 commented
Hey @shloch,
Thanks for picking this in the review. I have implemented the change as requested

2020-09-25 12:48 UTC, Torres-ssf approved these changes
### Milestone approved :+1: 
Hi @Phylis05 :hand: 
Great job on this milestone. You may merge the PR now.
Good luck with the next one.

Happy Coding :computer: 
**Sergio Torres**

2020-09-25 14:03 UTC, Phylis05 commented
Thanks @Torres-ssf  for the approval

2020-09-25 14:03 UTC, merged