Milestone four: Logic
phylischumba/Calculator-React pull request #4
Opened 2020-09-25 14:35 UTC by Phylis05

### Add logic App

- Added logic to the calculator application
- Fixed linter errors

2020-09-26 20:32 UTC, mosaaleb requested changes
#### Well done @Phylis05 :clap:

You have done all the requirements. Let's make sure before moving on that we return the result from the `operate` method.

Please handle this requirement and submit a new code review.

##### Muhammad Ebeid

2020-09-26 20:32 UTC, mosaaleb commented on src/logic/operate.js
> +  let result = 0;
- [ ] Should this function return the result? It sets the result but returns an undefined value. 
We could also get rid of the result variable, and return the result directly within the if-else body.

2020-09-27 22:09 UTC, jofer86 approved these changes
## `const PROJECT_STATUS = "APPROVED"` 🚀 🚀 🚀 
## :wave: :wave: Hello! I'm Jorge, and  I will be conducting this code review. Let me get a closer look 🔎 🔍 🔎 🔍 🕵🏼 
- Changes marked as **[OPTIONAL]** are not hard requirements but are nice to have.
- All to the required changes were completed as requested, this milestone is done, you  may move along.
--------------------------------------------------------------------
**Rock on**  🤘🏼 
**_Jorge Fernando Rincón Figueroa._** 
Technical Support Engineer.

2020-09-28 06:40 UTC, Phylis05 commented
Hey @jofer86, thanks for the code review and approving this PR.

2020-09-28 09:47 UTC, merged